/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarSelector: typeof import('./src/components/CarSelector.vue')['default']
    ChipSelect: typeof import('./src/components/ChipSelect.vue')['default']
    MyCarousel: typeof import('./src/components/MyCarousel.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PenaltyTable: typeof import('./src/components/PenaltyTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollWrapper: typeof import('./src/components/ScrollWrapper.vue')['default']
    TrackSelector: typeof import('./src/components/TrackSelector.vue')['default']
  }
}
