export default [
  // 文件夹名，英文简写，英文全写，LFM
  [
    'barcelona',
    'Barcelona',
    'Circuit de Barcelona-Catalunya',
    'Circuit de Catalunya',
  ],
  [
    'brands_hatch',
    'Brands Hatch',
    'Brands Hatch Circuit',
    'Brands Hatch Circuit',
  ],
  ['hungaroring', 'Hungaroring', 'Hungaroring', 'Hungaroring'],
  ['misano', 'Misano', 'Misano World Circuit', 'Misano'],
  ['monza', 'Monza', 'Monza Circuit', 'Autodromo Nazionale di Monza'],
  ['nurburgring', 'Nürburgring', 'Nürburgring', 'Nürburgring'],
  [
    'paul_ricard',
    'Paul Ricard',
    'Circuit Paul Ricard',
    'Circuit de Paul Ricard',
  ],
  ['silverstone', 'Silverstone', 'Silverstone', 'Silverstone'],
  [
    'spa',
    'Spa-Francorchamps',
    'Circuit de Spa-Francorchamps',
    'Circuit de Spa Francorchamps',
  ],
  [
    'valencia',
    'Valencia',
    'Circuit Ricardo Tormo Valencia',
    'Circuit Ricardo Tormo',
  ],
  ['zandvoort', 'Zandvoort', 'Circuit Zandvoort', 'Zandvoort'],
  ['zolder', 'Zolder', 'Circuit Zolder', 'Zolder'],
  [
    'nurburgring_24h',
    '24h Nürb',
    ' 24h Nürburgring',
    'Nürburgring Nordschleife 24h',
  ],
  [
    'imola',
    'Imola',
    'Autodromo Enzo e Dino Ferrari',
    'Autodromo Enzo e Dino Ferrari',
  ],
  [
    'red_bull_ring',
    'Red Bull Ring',
    'Red Bull Ring',
    'Spielberg - Red Bull Ring',
  ],
  ['oulton_park', 'Oulton Park', 'Oulton Park Circuit', 'Oulton Park'],
  ['snetterton', 'Snetterton', 'Snetterton Circuit', 'Snetterton'],
  ['donington', 'Donington Park', 'Donington Park', 'Donington Park'],
  ['cota', 'COTA', 'Circuit of the Americas', 'Circuit Of The Americas'],
  [
    'indianapolis',
    'Indianapolis',
    'Indianapolis Motor Speedway',
    'Indianapolis',
  ],
  [
    'watkins_glen',
    'Watkins Glen',
    'Watkins Glen International',
    'Watkins Glen',
  ],
  [
    'mount_panorama',
    'Mount Panorama',
    'Mount Panorama Circuit',
    'Mount Panorama Circuit',
  ],
  [
    'laguna_seca',
    'Laguna Seca',
    'WeatherTech Raceway Laguna Seca',
    'Laguna Seca',
  ],
  ['suzuka', 'Suzuka', 'Suzuka Circuit', 'Suzuka Circuit'],
  ['kyalami', 'Kyalami', 'Kyalami Grand Prix Circuit', 'Kyalami'],
]
