export default [
  // 文件夹名，英文简写，英文全写，LFM
  [
    'barcelona',
    'Barcelona',
    'Circuit de Barcelona-Catalunya',
    'Circuit de Catalunya',
    124,
  ],
  [
    'brands_hatch',
    'Brands Hatch',
    'Brands Hatch Circuit',
    'Brands Hatch Circuit',
    125,
  ],
  ['hungaroring', 'Hungaroring', 'Hungaroring', 'Hungaroring', 126],
  ['misano', 'Misano', 'Misano World Circuit', 'Misano', 127],
  ['monza', 'Monza', 'Monza Circuit', 'Autodromo Nazionale di Monza', 128],
  ['nurburgring', 'Nürburgring', 'Nürburgring', 'Nürburgring', 129],
  [
    'paul_ricard',
    'Paul Ricard',
    'Circuit Paul Ricard',
    'Circuit de Paul Ricard',
    130,
  ],
  ['silverstone', 'Silverstone', 'Silverstone', 'Silverstone', 131],
  [
    'spa',
    'Spa-Francorchamps',
    'Circuit de Spa-Francorchamps',
    'Circuit de Spa Francorchamps',
    132,
  ],
  [
    'valencia',
    'Valencia',
    'Circuit Ricardo Tormo Valencia',
    'Circuit Ricardo Tormo',
    155,
  ],
  ['zandvoort', 'Zandvoort', 'Circuit Zandvoort', 'Zandvoort', 135],
  ['zolder', 'Zolder', 'Circuit Zolder', 'Zolder', 133],
  [
    'nurburgring_24h',
    '24h Nürb',
    ' 24h Nürburgring',
    'Nürburgring Nordschleife 24h',
    249,
  ],
  [
    'imola',
    'Imola',
    'Autodromo Enzo e Dino Ferrari',
    'Autodromo Enzo e Dino Ferrari',
    134,
  ],
  [
    'red_bull_ring',
    'Red Bull Ring',
    'Red Bull Ring',
    'Spielberg - Red Bull Ring',
    223,
  ],
  ['oulton_park', 'Oulton Park', 'Oulton Park Circuit', 'Oulton Park', 140],
  ['snetterton', 'Snetterton', 'Snetterton Circuit', 'Snetterton', 142],
  ['donington', 'Donington Park', 'Donington Park', 'Donington Park', 141],
  ['cota', 'COTA', 'Circuit of the Americas', 'Circuit Of The Americas', 145],
  [
    'indianapolis',
    'Indianapolis',
    'Indianapolis Motor Speedway',
    'Indianapolis',
    143,
  ],
  [
    'watkins_glen',
    'Watkins Glen',
    'Watkins Glen International',
    'Watkins Glen',
    144,
  ],
  [
    'mount_panorama',
    'Mount Panorama',
    'Mount Panorama Circuit',
    'Mount Panorama Circuit',
    136,
  ],
  [
    'laguna_seca',
    'Laguna Seca',
    'WeatherTech Raceway Laguna Seca',
    'Laguna Seca',
    138,
  ],
  ['suzuka', 'Suzuka', 'Suzuka Circuit', 'Suzuka Circuit', 137],
  ['kyalami', 'Kyalami', 'Kyalami Grand Prix Circuit', 'Kyalami', 139],
]
